#
# Makefile for Chapter 03
#
# Type  make    to compile all the programs
# in the chapter 
#
all: fileinfo filesize ls1 ls2

clean:
	rm -f fileinfo filesize ls1 ls2


fileinfo: fileinfo.c 
	cc -g -o fileinfo fileinfo.c 

filesize: filesize.c 
	cc -g -o filesize filesize.c 

ls1: ls1.c 
	cc -g -o ls1 ls1.c 

ls2: ls2.c 
	cc -g -o ls2 ls2.c 
