#
#Makefile for Chapter 11
#
# Type  make    to compile all the programs
# in the chapter 
#
all: popen popen_ex3 popendemo rls rlsd testbdp timeclnt timeserv tinybc
#
clean:
	rm -f popen popen_ex3 popendemo rls rlsd testbdp timeclnt timeserv tinybc
#
#
popen: popen.c
	cc -g -o popen popen.c
#
popen_ex3: popen_ex3.c
	cc -g -o popen_ex3 popen_ex3.c
#
popendemo: popendemo.c
	cc -g -o popendemo popendemo.c
#
rls: rls.c
	cc -g -o rls rls.c
#
rlsd: rlsd.c
	cc -g -o rlsd rlsd.c
#
testbdp: testbdp.c
	cc -g -o testbdp testbdp.c
#
timeclnt: timeclnt.c
	cc -g -o timeclnt timeclnt.c
#
timeserv: timeserv.c
	cc -g -o timeserv timeserv.c
#
tinybc: tinybc.c
	cc -g -o tinybc tinybc.c
#
