#
# Makefile for Chapter 05
#
# Type  make    to compile all the programs
# in the chapter 
#
all: echostate listchars setecho showtty write0

clean:
	rm -f echostate listchars setecho showtty write0


echostate: echostate.c 
	cc -g -o echostate echostate.c 

listchars: listchars.c 
	cc -g -o listchars listchars.c 

setecho: setecho.c 
	cc -g -o setecho setecho.c 

showtty: showtty.c 
	cc -g -o showtty showtty.c 

write0: write0.c 
	cc -g -o write0 write0.c 
